// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NUMBER-0]
	_ = x[E-1]
	_ = x[PI-2]
	_ = x[ADD-3]
	_ = x[SUB-4]
	_ = x[MUL-5]
	_ = x[DIV-6]
	_ = x[EXP-7]
	_ = x[LOG-8]
	_ = x[LN-9]
	_ = x[SIN-10]
	_ = x[COS-11]
	_ = x[TAN-12]
	_ = x[ARCSIN-13]
	_ = x[ARCCOS-14]
	_ = x[ARCTAN-15]
	_ = x[SQRT-16]
	_ = x[LPAREN-17]
	_ = x[RPAREN-18]
}

const _TokenType_name = "NUMBEREPIADDSUBMULDIVEXPLOGLNSINCOSTANARCSINARCCOSARCTANSQRTLPARENRPAREN"

var _TokenType_index = [...]uint8{0, 6, 7, 9, 12, 15, 18, 21, 24, 27, 29, 32, 35, 38, 44, 50, 56, 60, 66, 72}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
